'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\140.81.58.14\public_share\system\CartonBoxLabel_mr400e_MLv4.mllay")>  _
        Public Property BagLabelLayoutFile() As String
            Get
                Return CType(Me("BagLabelLayoutFile"),String)
            End Get
            Set
                Me("BagLabelLayoutFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\140.81.58.14\public_share\system\CartonBoxLabel_mr400e_MLv4.mllay")>  _
        Public Property CartonBoxLabelLayoutFile() As String
            Get
                Return CType(Me("CartonBoxLabelLayoutFile"),String)
            End Get
            Set
                Me("CartonBoxLabelLayoutFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Program Files\MLmeControl\PrinterFiles\")>  _
        Public Property PrinterPath_PATH() As String
            Get
                Return CType(Me("PrinterPath_PATH"),String)
            End Get
            Set
                Me("PrinterPath_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DRV:SATO SR408")>  _
        Public Property BarcodePrinter_Setting() As String
            Get
                Return CType(Me("BarcodePrinter_Setting"),String)
            End Get
            Set
                Me("BarcodePrinter_Setting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CP91040N")>  _
        Public Property Org() As String
            Get
                Return CType(Me("Org"),String)
            End Get
            Set
                Me("Org") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CP91050N")>  _
        Public Property Cores() As String
            Get
                Return CType(Me("Cores"),String)
            End Get
            Set
                Me("Cores") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CP91060N")>  _
        Public Property Chips() As String
            Get
                Return CType(Me("Chips"),String)
            End Get
            Set
                Me("Chips") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CP90670N")>  _
        Public Property Hemlock_Org() As String
            Get
                Return CType(Me("Hemlock_Org"),String)
            End Get
            Set
                Me("Hemlock_Org") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CP90680N")>  _
        Public Property Hemlock_Cores() As String
            Get
                Return CType(Me("Hemlock_Cores"),String)
            End Get
            Set
                Me("Hemlock_Cores") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CP90690N")>  _
        Public Property Hemlock_Chips() As String
            Get
                Return CType(Me("Hemlock_Chips"),String)
            End Get
            Set
                Me("Hemlock_Chips") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CP90650N")>  _
        Public Property Hemlock_Fragments() As String
            Get
                Return CType(Me("Hemlock_Fragments"),String)
            End Get
            Set
                Me("Hemlock_Fragments") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Serial_PortId() As String
            Get
                Return CType(Me("Serial_PortId"),String)
            End Get
            Set
                Me("Serial_PortId") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1200,n,8,1")>  _
        Public Property Serial_Port_Setting() As String
            Get
                Return CType(Me("Serial_Port_Setting"),String)
            End Get
            Set
                Me("Serial_Port_Setting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("202")>  _
        Public Property MIS_WarehouseId() As String
            Get
                Return CType(Me("MIS_WarehouseId"),String)
            End Get
            Set
                Me("MIS_WarehouseId") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property MIS_FabId() As String
            Get
                Return CType(Me("MIS_FabId"),String)
            End Get
            Set
                Me("MIS_FabId") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("KOM")>  _
        Public Property MIS_CustomerId() As String
            Get
                Return CType(Me("MIS_CustomerId"),String)
            End Get
            Set
                Me("MIS_CustomerId") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TD")>  _
        Public Property DB_DbName() As String
            Get
                Return CType(Me("DB_DbName"),String)
            End Get
            Set
                Me("DB_DbName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("td")>  _
        Public Property DB_Username() As String
            Get
                Return CType(Me("DB_Username"),String)
            End Get
            Set
                Me("DB_Username") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("td")>  _
        Public Property DB_Password() As String
            Get
                Return CType(Me("DB_Password"),String)
            End Get
            Set
                Me("DB_Password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property TableId() As String
            Get
                Return CType(Me("TableId"),String)
            End Get
            Set
                Me("TableId") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CP91070N")>  _
        Public Property Fragments() As String
            Get
                Return CType(Me("Fragments"),String)
            End Get
            Set
                Me("Fragments") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Specimen() As String
            Get
                Return CType(Me("Specimen"),String)
            End Get
            Set
                Me("Specimen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property OtherDefect() As String
            Get
                Return CType(Me("OtherDefect"),String)
            End Get
            Set
                Me("OtherDefect") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Prasad\Mywork\Arya Global Projects\VB.NET\TD_Helmock_VB.NET_MDB\td_v10.mdb")>  _
        Public Property MDB_File_PATH() As String
            Get
                Return CType(Me("MDB_File_PATH"),String)
            End Get
            Set
                Me("MDB_File_PATH") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Prasad\Mywork\Arya Global Projects\VB.NET\TD_Helmock_VB.NET_MDB\mis_rpt_tbl_v1" &
            "0.mdb")>
        Public Property RPT_MDB_File_Path() As String
            Get
                Return CType(Me("RPT_MDB_File_Path"), String)
            End Get
            Set
                Me("RPT_MDB_File_Path") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Prasad\Mywork\Arya Global Projects\VB.NET\TD_Helmock_VB.NET_MDB\TD_Acceptance_"& _ 
            "V10_mdb.NET\ReportTD_Material.rdlx")>  _
        Public Property TdMaterialReportFilePath() As String
            Get
                Return CType(Me("TdMaterialReportFilePath"),String)
            End Get
            Set
                Me("TdMaterialReportFilePath") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Project1.My.MySettings
            Get
                Return Global.Project1.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
